baseURL = 'https://yuandata.github.io/CodeTutor/'
languageCode = 'en-us'
title = 'Code Tutor'
theme = 'Augustus'

[params]
	dateFormat = "Oct 11, 2023" 
	
[menu]
	[[menu.main]]
		Name = "Home"
		URL = "#"
		weight = 1
	
	[[menu.main]]
		Name = "About"
		URL = "#four-features"
		weight = 2
		
	[[menu.main]]
		Name = "Plans"
		URL = "#pricing-section"
		weight = 3
		
[params.content]
	LeadTitle = "程式設計 家教課程"
	LeadDescription = "零基礎開始學習寫程式，手把手教學，從認識網頁架構到完成簡單專案。"
	ButtonCaption = "課 程 方 案"
	ButtonURL = "#pricing-section"

################### 最多四項 Feature Columns ####################

[[params.feature]]
	FeatureTitle = "深入淺出 程式設計"
	FeatureDescription = "透過系統學習與實際項目，來探索自己對程式設計的興趣的學習者設計。透過從基礎開始，逐步建立知識結構。"
	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "軟體產業 轉職指引"
	FeatureDescription = "透過最新技術的學習和技能提升，幫助增強職場競爭力，從而實現更高薪、更時間自主的工作機會。"
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "量身打造 實踐計劃"
	FeatureDescription = "逐堂學習進度和活動，幫助有效地吸收知識並扎實進行實作，打下堅實的基礎，提升即戰力。"
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "自學能力 領航培訓"
	FeatureDescription = "導覽程式語言、系統概論和演算法。培養邏輯思維和自學能力，理解程式設計背後的思考邏輯，達成學以致用。"
	FeatureImage = "images/feature-4.png"
	
################### 最多三項 Pricing Columns ####################

[[params.pricing]]
	PricingTitle = "基礎課程"
	PricingRate = "程式設計入門"	
	ButtonCaption = "✨線上教材試閱"
	ButtonHref = "https://yuandata.github.io/Code/golang/class-07/"
	[[params.pricing.Features]]
		Description = "Python 語言開發實戰案例"
	[[params.pricing.Features]]
		Description = "數據結構與LeetCode解題"
	[[params.pricing.Features]]
		Description = "教材無期限閱覽"

[[params.pricing]]
	PricingTitle = "轉職課程"
	PricingRate = "建立後端技能"
	ButtonCaption = "立 即 參 與"
	ButtonHref = "#contact-section"
	[[params.pricing.Features]]
		Description = "Go 簡易 HTTP 伺服器"
	[[params.pricing.Features]]
		Description = "Go 專案CI/CD(持續集成/持續部署)"
	[[params.pricing.Features]]
		Description = "教材無期限閱覽"
	[[params.pricing.Features]]
		Description = "加入學員專屬社群，即時交流解題"

[[params.pricing]]
	PricingTitle = "實務課程"
	PricingRate = "軟體測試實務"
	ButtonCaption = "立 即 參 與"
	ButtonHref = "#contact-section"
	[[params.pricing.Features]]
		Description = "自動化測試與測試驅動開發(TDD)"
	[[params.pricing.Features]]
		Description = "掌握Pytest框架"
	[[params.pricing.Features]]
		Description = "教材無期限閱覽"
	[[params.pricing.Features]]
		Description = "加入學員專屬社群，即時交流解題"