baseURL = 'https://yuandata.github.io/CodeTutor/'
languageCode = 'en-us'
title = 'Code Tutor'
theme = 'Augustus'

[params]
	dateFormat = "Nov 11, 2023" 
	google_analytics_id = "GA-"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		URL = "#"
		weight = 1
	
	[[menu.main]]
		Name = "About us"
		URL = "#"
		weight = 2
		
	[[menu.main]]
		Name = "Support"
		URL = "#"
		weight = 3
		
[params.social]
	PythonURL = "#"
	GitHubURL = "#"
	GitLabURL = "#"
		
[params.content]
	LeadTitle = "ç¨‹å¼è¨­è¨ˆ å®¶æ•™èª²"
	LeadDescription = "ä¸€å€‹æœˆå¾é›¶åŸºç¤é–‹å§‹å­¸ç¿’å¯«ç¨‹å¼ï¼Œæ‰‹æŠŠæ‰‹æ•™å­¸ï¼Œå¾èªè­˜ç¶²é æ¶æ§‹åˆ°å®Œæˆç°¡å–®å°ˆæ¡ˆã€‚"
	ButtonCaption = "èª²ç¨‹æ–¹æ¡ˆ"
	ButtonURL = "#pricing-section"

################### æœ€å¤šå››é … Feature Columns ####################

[[params.feature]]
	FeatureTitle = "æ·±å…¥æ·ºå‡ºç¨‹å¼è¨­è¨ˆ"
	FeatureDescription = "æœ¬å®¶æ•™èª²ç¨‹å°ˆç‚ºå¸Œæœ›é€éç³»çµ±å­¸ç¿’èˆ‡å¯¦éš›é …ç›®ï¼Œä¾†æ¢ç´¢è‡ªå·±å°ç¨‹å¼è¨­è¨ˆçš„èˆˆè¶£çš„å­¸ç¿’è€…è¨­è¨ˆã€‚é€éå¾åŸºç¤é–‹å§‹ï¼Œé€æ­¥å»ºç«‹çŸ¥è­˜çµæ§‹ã€‚"
	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "æ•¸ä½ç”¢æ¥­è½‰è·æŒ‡å¼•"
	FeatureDescription = "é€éæœ€æ–°æŠ€è¡“çš„å­¸ç¿’å’ŒæŠ€èƒ½æå‡ï¼Œå¹«åŠ©å€‹äººå¢å¼·è·å ´ç«¶çˆ­åŠ›ï¼Œå¾è€Œå¯¦ç¾æ›´é«˜è–ªã€æ›´å…·éˆæ´»æ€§å·¥ä½œæ©Ÿæœƒçš„è½‰è®Šã€‚"
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "é‡èº«æ‰“é€ å¯¦è¸è¨ˆåŠƒ"
	FeatureDescription = "æœ¬å®¶æ•™èª²ç¨‹è¨­è¨ˆé€å ‚å­¸ç¿’é€²åº¦å’Œæ´»å‹•ï¼Œå¹«åŠ©æœ‰æ•ˆåœ°å¸æ”¶çŸ¥è­˜ä¸¦ç©©æ­¥æå‡å­¸ç¿’æ•ˆç‡ã€‚ä¸¦æ¡ç”¨OutPutå¾ªç’°æ¨¡å¼ï¼Œå”åŠ©å­¸å“¡æ‰“ä¸‹å …å¯¦çš„åŸºç¤ï¼Œå¿«é€Ÿé€²è¡Œå¯¦ä½œã€‚"
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "é‹ç®—æ€ç¶­èˆ‡è‡ªå­¸èƒ½åŠ›è¨“ç·´"
	FeatureDescription = "æ·±å…¥æ·ºå‡ºå°è¦½ç¨‹å¼èªè¨€ã€ç³»çµ±æ¦‚è«–å’Œæ¼”ç®—æ³•ã€‚åŸ¹é¤Šå­¸å“¡çš„é‚è¼¯æ€ç¶­å’Œè‡ªå­¸èƒ½åŠ›ï¼Œç†è§£ç¨‹å¼è¨­è¨ˆèƒŒå¾Œçš„æ€è€ƒé‚è¼¯ï¼Œé”æˆå­¸ä»¥è‡´ç”¨ã€‚"
	FeatureImage = "images/feature-4.png"
	
################### æœ€å¤šä¸‰é … Pricing Columns ####################

[[params.pricing]]
	PricingTitle = "åŸºç¤èª²ç¨‹"
	PricingRate = "ç¨‹å¼è¨­è¨ˆå…¥é–€"	
	ButtonCaption = "ğŸ”¥ é¦¬ä¸Šå ±å"
	[[params.pricing.Features]]
		Description = "Python èªè¨€é–‹ç™¼å¯¦æˆ°æ¡ˆä¾‹"
	[[params.pricing.Features]]
		Description = "æ•™æç„¡æœŸé™é–±è¦½"
	[[params.pricing.Features]]
		Description = "åŠ å…¥å­¸å“¡å°ˆå±¬ç¤¾ç¾¤ï¼Œå³æ™‚äº¤æµè§£é¡Œ"	

[[params.pricing]]
	PricingTitle = "è½‰è·èª²ç¨‹"
	PricingRate = "å»ºç«‹å¾Œç«¯æŠ€èƒ½"
	ButtonCaption = "âœ¨ é¦¬ä¸Šå ±å"
	[[params.pricing.Features]]
		Description = "Go ç°¡æ˜“ HTTP ä¼ºæœå™¨"
	[[params.pricing.Features]]
		Description = "Go å°ˆæ¡ˆæŒçºŒæ•´åˆæ¸¬è©¦éƒ¨ç½²"
	[[params.pricing.Features]]
		Description = "æ•™æç„¡æœŸé™é–±è¦½"
	[[params.pricing.Features]]
		Description = "åŠ å…¥å­¸å“¡å°ˆå±¬ç¤¾ç¾¤ï¼Œå³æ™‚äº¤æµè§£é¡Œ"
